name: SurvivalGames
author: LegendOfMCPE
api: [1.0.0]
version: 1.0
load: POSTWORLD
main: survivalgames\Main

permissions:
    sg:
        default: op
        description: "Все команды SurvivalGames."
        children:
            sg.arena:
                default: op
                description: "Сделать что либо на\в арене."
                sg.arena.leave:
                    default: op
                    description: "Выйти с арены."
            sg.lobby:
                default: op
                description: "Сделать что либо на\в лобном."
                children:
                    sg.lobby.leave:
                        default: op
                        description: "Выйти с лобного."
                                            
